// Code generated by Slice Machine. DO NOT EDIT.

import Image from './Image';
import LogoSection from './LogoSection';
import Quote from './Quote';
import Text from './Text';

export {
	Image,
	LogoSection,
	Quote,
	Text,
};

export const components = {
	image: Image,
	logo_section: LogoSection,
	quote: Quote,
	text: Text,
};
